- name: "Installing Apache"
  hosts: client1
  become: yes
  tasks:
      - name: "Install apache2 package"
        apt:
           name: apache2
           state: latest
           update_cache: yes
      - name: "Restart apache2 services"
        service:
            name: apache2
            state: reloaded
            enabled: true
      - name: "Installing php"
        apt:
            name: php
            state: latest
            update_cache: yes
      - name: "Creating info page"
        copy:
            content: "<?php phpinfo(); ?>"
            dest: /var/www/html/index.php

      - name: "Install mariadb package"
        apt:
            name: mariadb-server
            state: latest
            update_cache: yes
      - name: "Creating index.html page"
        copy:
            content: "<h1>WELCOME</h1>"
            dest: /var/www/html/index.html
      - name: "Restart mariadb service"
        service:
            name: mariadb
            state: restarted
            enabled: true
      - name: "Download wordpress"
        get_url:
              url: https://wordpress.org/latest.tar.gz
              dest: /tmp/wordpress.tar.gz
                                                 
